import { Company, Property, Profile, Task, Routine, TaskRequest, AuditLog, Notification } from '../types';

export const DEMO_COMPANY_ID = 'comp-demo-001';
export const DEMO_PROPERTY_ID = 'prop-demo-001';

export const initialCompanies: Company[] = [
  {
    id: DEMO_COMPANY_ID,
    legal_name: 'CAST Serviços Técnicos e Facilities Ltda',
    trade_name: 'CAST Serviços Técnicos',
    cnpj: '12.345.678/0001-90',
    email: 'empresa@cast.com',
    phone: '(11) 98765-4321',
    address: 'Av. Paulista, 1000 - Cj 52',
    city: 'São Paulo',
    state: 'SP',
    responsible_name: 'Mariana Gestão',
    responsible_email: 'mariana@cast.com',
    responsible_phone: '(11) 98888-1111',
    status: 'Ativa',
    google_drive_folder_name: 'CAST - Documentos e Relatórios',
    google_drive_email: 'empresa@cast.com',
    google_drive_folder_url: 'https://drive.google.com/drive/folders/cast-servicos-documentos',
    google_drive_connected: false,
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'comp-demo-002',
    legal_name: 'Facilitando Gestão Predial Eireli',
    trade_name: 'Facilitando Condomínios',
    cnpj: '98.765.432/0001-10',
    email: 'contato@facilitando.com.br',
    phone: '(21) 97777-2222',
    address: 'Rua Visconde de Pirajá, 300',
    city: 'Rio de Janeiro',
    state: 'RJ',
    responsible_name: 'Carlos Oliveira',
    responsible_email: 'carlos@facilitando.com.br',
    responsible_phone: '(21) 97777-3333',
    status: 'Ativa',
    created_at: '2026-02-10T10:00:00Z',
    updated_at: '2026-02-10T10:00:00Z',
  }
];

export const initialProperties: Property[] = [
  {
    id: DEMO_PROPERTY_ID,
    company_id: DEMO_COMPANY_ID,
    name: 'Residencial Modelo',
    address: 'Rua das Flores, 500 - Jardim América',
    city: 'São Paulo',
    state: 'SP',
    status: 'Ativo',
    created_at: '2026-01-16T09:00:00Z',
    updated_at: '2026-01-16T09:00:00Z',
  },
  {
    id: 'prop-demo-002',
    company_id: DEMO_COMPANY_ID,
    name: 'Edifício Horizon Blue',
    address: 'Alameda Santos, 1200',
    city: 'São Paulo',
    state: 'SP',
    status: 'Ativo',
    created_at: '2026-01-20T11:00:00Z',
    updated_at: '2026-01-20T11:00:00Z',
  }
];

export const initialProfiles: Profile[] = [
  {
    id: 'user-dev-01',
    auth_user_id: 'auth-dev-01',
    role: 'DEV',
    name: 'Administrador CAST (Admin Global)',
    email: 'cast.servicostecnicos@gmail.com',
    password: 'cast@2468',
    phone: '(11) 99999-0000',
    cpf: '111.222.333-44',
    city: 'São Paulo',
    state: 'SP',
    status: 'Ativo',
    notes: 'Desenvolvedor e administrador geral da plataforma CAST Zeladoria Pro.',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'user-empresa-01',
    auth_user_id: 'auth-empresa-01',
    company_id: DEMO_COMPANY_ID,
    role: 'EMPRESA',
    name: 'Mariana Gestão (CAST)',
    email: 'empresa@cast.com',
    password: 'cast@2468',
    phone: '(11) 98765-4321',
    cpf: '222.333.444-55',
    city: 'São Paulo',
    state: 'SP',
    status: 'Ativo',
    notes: 'Coordenadora operacional e gestora de zeladoria predial.',
    created_at: '2026-01-15T08:00:00Z',
    updated_at: '2026-01-15T08:00:00Z',
  },
  {
    id: 'user-zelador-01',
    auth_user_id: 'auth-zelador-01',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    role: 'ZELADOR',
    name: 'João Silva (Zelador CAST)',
    email: 'zelador@cast.com',
    password: 'cast@2468',
    phone: '(11) 97777-6666',
    cpf: '333.444.555-66',
    badge_number: 'ZEL-0042',
    birth_date: '1985-06-12',
    city: 'São Paulo',
    state: 'SP',
    status: 'Ativo',
    notes: 'Zelador líder no Residencial Modelo. Turno da manhã.',
    created_at: '2026-01-17T08:30:00Z',
    updated_at: '2026-01-17T08:30:00Z',
  },
  {
    id: 'user-adm-01',
    auth_user_id: 'auth-adm-01',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    role: 'ADM_PREDIAL',
    name: 'Roberto Mendes (ADM Predial CAST)',
    email: 'adm@cast.com',
    password: 'cast@2468',
    phone: '(11) 96666-5555',
    cpf: '555.666.777-88',
    city: 'São Paulo',
    state: 'SP',
    status: 'Ativo',
    notes: 'Síndico Profissional / Administrador Predial do Residencial Modelo.',
    created_at: '2026-01-16T10:00:00Z',
    updated_at: '2026-01-16T10:00:00Z',
  }
];

export const initialTasks: Task[] = [
  {
    id: 'task-001',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    title: 'Limpeza do salão de festas',
    description: 'Realizar higienização completa após evento no fim de semana, incluindo copa, banheiros e piso.',
    category: 'Limpeza',
    priority: 'NORMAL',
    status: 'CONCLUIDA',
    assigned_to: 'user-zelador-01',
    created_by: 'user-empresa-01',
    scheduled_date: '2026-09-24',
    scheduled_time: '08:00',
    deadline: '2026-09-24T12:00:00Z',
    location: 'Salão de Festas - Térreo',
    completed_at: '2026-09-24T11:15:00Z',
    completed_by: 'user-zelador-01',
    completion_description: 'Realizada limpeza do salão de festas, incluindo varrição, lavagem do piso, higienização dos banheiros e retirada dos resíduos recicláveis.',
    photos: [
      {
        id: 'photo-01',
        task_id: 'task-001',
        storage_path: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&auto=format&fit=crop&q=80',
        uploaded_by: 'user-zelador-01',
        created_at: '2026-09-24T11:14:00Z',
      }
    ],
    created_at: '2026-09-23T14:00:00Z',
    updated_at: '2026-09-24T11:15:00Z',
  },
  {
    id: 'task-002',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    title: 'Verificação da iluminação',
    description: 'Checar refletores dos jardins e luminárias de emergência dos blocos A e B.',
    category: 'Manutenção',
    priority: 'ALTA',
    status: 'EM_ANDAMENTO',
    assigned_to: 'user-zelador-01',
    created_by: 'user-empresa-01',
    scheduled_date: '2026-09-24',
    scheduled_time: '14:00',
    deadline: '2026-09-24T17:00:00Z',
    location: 'Jardins e Escadarias Bloco A/B',
    created_at: '2026-09-24T07:30:00Z',
    updated_at: '2026-09-24T14:05:00Z',
  },
  {
    id: 'task-003',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    title: 'Limpeza da garagem',
    description: 'Varrição e desobstrução de canaletas do subsolo 1 e 2.',
    category: 'Limpeza',
    priority: 'URGENTE',
    status: 'PENDENTE',
    assigned_to: 'user-zelador-01',
    created_by: 'user-empresa-01',
    scheduled_date: '2026-09-24',
    scheduled_time: '16:00',
    deadline: '2026-09-24T18:30:00Z',
    location: 'Subsolos G1 e G2',
    created_at: '2026-09-24T08:00:00Z',
    updated_at: '2026-09-24T08:00:00Z',
  },
  {
    id: 'task-004',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    title: 'Retirada de resíduos',
    description: 'Conferir lixeiras dos andares e acondicionar no depósito central para coleta municipal.',
    category: 'Rotina',
    priority: 'NORMAL',
    status: 'ACEITA',
    assigned_to: 'user-zelador-01',
    created_by: 'user-empresa-01',
    scheduled_date: '2026-09-24',
    scheduled_time: '10:00',
    location: 'Depósito Central de Lixo',
    created_at: '2026-09-24T07:00:00Z',
    updated_at: '2026-09-24T09:45:00Z',
  },
  {
    id: 'task-005',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    title: 'Inspeção da área externa',
    description: 'Vistoria das calçadas, portões de pedestres e lixeiras externas.',
    category: 'Vistoria',
    priority: 'BAIXA',
    status: 'ATRASADA',
    assigned_to: 'user-zelador-01',
    created_by: 'user-empresa-01',
    scheduled_date: '2026-09-23',
    scheduled_time: '15:00',
    deadline: '2026-09-23T18:00:00Z',
    location: 'Perímetro Externo e Portaria',
    created_at: '2026-09-23T10:00:00Z',
    updated_at: '2026-09-24T06:00:00Z',
  }
];

export const initialRoutines: Routine[] = [
  {
    id: 'rot-001',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    name: 'Limpeza da área externa',
    description: 'Varrição e recolhimento de folhas e resíduos em volta da portaria e jardins frontais.',
    location: 'Entrada Principal e Jardins',
    category: 'Limpeza',
    priority: 'NORMAL',
    assigned_to: 'user-zelador-01',
    frequency: 'diária',
    scheduled_time: '08:00',
    start_date: '2026-01-01',
    active: true,
    created_at: '2026-01-18T10:00:00Z',
    updated_at: '2026-01-18T10:00:00Z',
  },
  {
    id: 'rot-002',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    name: 'Verificação dos elevadores e bombas',
    description: 'Inspeção auditiva, verificação de painéis e nível da caixa de água superior.',
    location: 'Casa de Máquinas e Barrilete',
    category: 'Manutenção Preventiva',
    priority: 'ALTA',
    assigned_to: 'user-zelador-01',
    frequency: 'semanal',
    days_of_week: ['seg', 'qui'],
    scheduled_time: '09:00',
    start_date: '2026-01-01',
    active: true,
    created_at: '2026-01-18T10:30:00Z',
    updated_at: '2026-01-18T10:30:00Z',
  },
  {
    id: 'rot-003',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    name: 'Inspeção de extintores e mangueiras de incêndio',
    description: 'Checar lacres, manômetros e desobstrução das caixas de hidrante dos pavimentos.',
    location: 'Todos os pavimentos Bloco A e B',
    category: 'Segurança Predial',
    priority: 'ALTA',
    assigned_to: 'user-zelador-01',
    frequency: 'mensal',
    scheduled_time: '14:00',
    start_date: '2026-01-01',
    active: true,
    created_at: '2026-01-18T11:00:00Z',
    updated_at: '2026-01-18T11:00:00Z',
  }
];

export const initialRequests: TaskRequest[] = [
  {
    id: 'req-001',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    requested_by: 'user-adm-01',
    title: 'Troca de lâmpada no hall do 4º andar',
    description: 'Moradores do 402 relataram que a lâmpada do hall está piscando e com ruído.',
    location: 'Hall do 4º andar - Bloco B',
    priority: 'NORMAL',
    desired_date: '2026-09-24',
    desired_time: '15:00',
    notes: 'Chave do alçapão com o porteiro.',
    status: 'SOLICITADA',
    created_at: '2026-09-24T08:30:00Z',
    updated_at: '2026-09-24T08:30:00Z',
  },
  {
    id: 'req-002',
    company_id: DEMO_COMPANY_ID,
    property_id: DEMO_PROPERTY_ID,
    requested_by: 'user-adm-01',
    title: 'Limpeza pós-obra na academia',
    description: 'Terminou a pintura das paredes da academia, necessário passar pano e limpar espelhos.',
    location: 'Espaço Fitness - Mezanino',
    priority: 'ALTA',
    desired_date: '2026-09-25',
    desired_time: '09:00',
    status: 'APROVADA',
    created_at: '2026-09-23T16:00:00Z',
    updated_at: '2026-09-24T08:00:00Z',
  }
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-001',
    company_id: DEMO_COMPANY_ID,
    user_id: 'user-empresa-01',
    user_name: 'Mariana Gestão',
    action: 'login',
    entity_type: 'auth',
    entity_id: 'user-empresa-01',
    created_at: '2026-09-24T07:15:00Z',
  },
  {
    id: 'log-002',
    company_id: DEMO_COMPANY_ID,
    user_id: 'user-zelador-01',
    user_name: 'João Silva',
    action: 'conclusão de tarefa',
    entity_type: 'task',
    entity_id: 'task-001',
    created_at: '2026-09-24T11:15:00Z',
  }
];

export const initialNotifications: Notification[] = [
  {
    id: 'notif-001',
    company_id: DEMO_COMPANY_ID,
    user_id: 'user-empresa-01',
    type: 'alert',
    title: 'Nova solicitação recebida',
    message: 'Roberto Mendes solicitou: Troca de lâmpada no hall do 4º andar.',
    read: false,
    created_at: '2026-09-24T08:30:00Z',
  },
  {
    id: 'notif-002',
    company_id: DEMO_COMPANY_ID,
    user_id: 'user-empresa-01',
    type: 'success',
    title: 'Tarefa concluída por João Silva',
    message: 'A tarefa "Limpeza do salão de festas" foi concluída com foto comprobatória.',
    read: true,
    created_at: '2026-09-24T11:15:00Z',
  },
  {
    id: 'notif-003',
    company_id: DEMO_COMPANY_ID,
    user_id: 'user-zelador-01',
    type: 'info',
    title: 'Nova tarefa atribuída',
    message: 'Você recebeu a tarefa urgente: Limpeza da garagem.',
    read: false,
    created_at: '2026-09-24T08:00:00Z',
  }
];
